// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Splendor.Infrastructure.Persistence;

#nullable disable

namespace Splendor.Infrastructure.Migrations
{
    [DbContext(typeof(ReadModelsContext))]
    [Migration("20260115150833_UpdatePlayerIdToString")]
    partial class UpdatePlayerIdToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Splendor.Application.ReadModels.GameView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentPlayerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameViews");
                });

            modelBuilder.Entity("Splendor.Application.ReadModels.PlayerView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("GameViewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameViewId");

                    b.ToTable("PlayerViews");
                });

            modelBuilder.Entity("Splendor.Application.ReadModels.GameView", b =>
                {
                    b.OwnsOne("Splendor.Domain.ValueObjects.GemCollection", "MarketGems", b1 =>
                        {
                            b1.Property<Guid>("GameViewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Diamond")
                                .HasColumnType("int");

                            b1.Property<int>("Emerald")
                                .HasColumnType("int");

                            b1.Property<int>("Gold")
                                .HasColumnType("int");

                            b1.Property<int>("Onyx")
                                .HasColumnType("int");

                            b1.Property<int>("Ruby")
                                .HasColumnType("int");

                            b1.Property<int>("Sapphire")
                                .HasColumnType("int");

                            b1.HasKey("GameViewId");

                            b1.ToTable("GameViews");

                            b1.WithOwner()
                                .HasForeignKey("GameViewId");
                        });

                    b.Navigation("MarketGems")
                        .IsRequired();
                });

            modelBuilder.Entity("Splendor.Application.ReadModels.PlayerView", b =>
                {
                    b.HasOne("Splendor.Application.ReadModels.GameView", null)
                        .WithMany("Players")
                        .HasForeignKey("GameViewId");

                    b.OwnsOne("Splendor.Domain.ValueObjects.GemCollection", "Gems", b1 =>
                        {
                            b1.Property<string>("PlayerViewId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Diamond")
                                .HasColumnType("int");

                            b1.Property<int>("Emerald")
                                .HasColumnType("int");

                            b1.Property<int>("Gold")
                                .HasColumnType("int");

                            b1.Property<int>("Onyx")
                                .HasColumnType("int");

                            b1.Property<int>("Ruby")
                                .HasColumnType("int");

                            b1.Property<int>("Sapphire")
                                .HasColumnType("int");

                            b1.HasKey("PlayerViewId");

                            b1.ToTable("PlayerViews");

                            b1.WithOwner()
                                .HasForeignKey("PlayerViewId");
                        });

                    b.Navigation("Gems")
                        .IsRequired();
                });

            modelBuilder.Entity("Splendor.Application.ReadModels.GameView", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
